### ISSUE TITLE
Demo无法运行

### ISSUE THREAD

**Issue by weiliang-Zhang** [weex-plugins/weex-chart#3]
demo在模拟器上运行后，点击任一目录，无法跳转到相应的图表，提示“很抱歉，weex已停止运行”。

**Comment by samyzh** [comment]
我这边也是，直接报错；
``` java

03-21 10:17:11.947 12039-12054/com.alibaba.weex D/weex: callJS >>>> instanceId:2function:callJS tasks:[{"data":"2","type":2},{"data":"[{\"args\":[4,{},true],\"method\":\"callback\"}]","type":3}]
03-21 10:17:11.948 12039-12054/com.alibaba.weex D/weex: [WXBridgeManager] callNative >>>> instanceId:2, tasks:[{"module":"dom","method":"updateFinish","args":[]}], callback:-1
03-21 10:17:11.950 12039-12039/com.alibaba.weex E/art: No implementation found for java.lang.String com.taobao.gcanvas.GCanvasJNI.getAllParameter(java.lang.String) (tried Java_com_taobao_gcanvas_GCanvasJNI_getAllParameter and Java_com_taobao_gcanvas_GCanvasJNI_getAllParameter__Ljava_lang_String_2)
03-21 10:17:11.950 12039-12039/com.alibaba.weex E/SafeRunnable: SafeRunnable run throw expection:java.lang.reflect.InvocationTargetException
03-21 10:17:11.950 12039-12039/com.alibaba.weex D/AndroidRuntime: Shutting down VM
03-21 10:17:11.951 12039-12039/com.alibaba.weex E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.alibaba.weex, PID: 12039
                                                                  java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                      at com.taobao.weex.bridge.NativeInvokeHelper$1.run(NativeInvokeHelper.java:236)
                                                                      at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.taobao.weex.bridge.MethodInvoker.invoke(MethodInvoker.java:232)
                                                                      at com.taobao.weex.bridge.NativeInvokeHelper$1.run(NativeInvokeHelper.java:234)
                                                                      at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234) 
                                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                   Caused by: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.taobao.gcanvas.GCanvasJNI.getAllParameter(java.lang.String) (tried Java_com_taobao_gcanvas_GCanvasJNI_getAllParameter and Java_com_taobao_gcanvas_GCanvasJNI_getAllParameter__Ljava_lang_String_2)
                                                                      at com.taobao.gcanvas.GCanvasJNI.getAllParameter(Native Method)
                                                                      at com.taobao.gcanvas.GCanvas.executeDelegate(GCanvas.java:680)
                                                                      at com.taobao.gcanvas.GCanvas.executeForWeex(GCanvas.java:347)
                                                                      at com.taobao.weex.ui.module.GcanvasModule.execGcanvasCMD(GcanvasModule.java:858)
                                                                      at com.taobao.weex.ui.module.GcanvasModule.enable(GcanvasModule.java:376)
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.taobao.weex.bridge.MethodInvoker.invoke(MethodInvoker.java:232) 
                                                                      at com.taobao.weex.bridge.NativeInvokeHelper$1.run(NativeInvokeHelper.java:234) 
                                                                      at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234) 
                                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
03-21 10:17:11.970 12039-12054/com.alibaba.weex D/weex: callJS >>>> instanceId:2function:callJS tasks:[{"data":"2","type":2},{"data":"[{\"args\":[4,{},true],\"method\":\"callback\"}]","type":3}]
03-21 10:17:11.983 12039-12054/com.alibaba.weex D/weex: [WXBridgeManager] callNative >>>> instanceId:2, tasks:[{"module":"dom","method":"updateFinish","args":[]}], callback:-1
03-21 10:17:11.990 12039-12045/com.alibaba.weex W/art: Suspending all threads took: 5.129ms
```
